version: '3.9'
services:
  bind9:
    container_name: bind9
    restart: always
    ports:
      - '53:53/udp'
      - '53:53/tcp'
      - '127.0.0.1:953:953/tcp'
    volumes:
      - ./config:/etc/bind 
      - ./cache:/var/cache/bind
      - ./lib:/var/lib/bind
      - ./log:/var/log/bind
    image: 'internetsystemsconsortium/bind9:9.18'


  dhcpd:
    build:
      dockerfile: Dockerfile.dhcp
    container_name: dhcpd
    networks:
      dhcp:
        ipv4_address: "172.23.0.2"
    volumes:
      - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
      - ./dhcp/dhcpd.leases:/var/lib/dhcp/dhcpd.leases
#	dnssec-keygen -a HMAC-MD5 -b 128 -n
      - ./config/rndc.key:/etc/dhcp/rndc.key:ro
    depends_on:
      - bind9

networks:
  dhcp:
    ipam:
      config:
        - subnet: "172.23.0.0/16"

